resources:
- name: every-1m
  type: time
  source: {interval: 1m}
- name: git-resource
  type: git
  source:
    uri: git@github.com:UWTech/foo-task-examples.git
    branch: master
jobs:
- name: navi
  plan:
  - get: git-resource
    trigger: true 
  - get: every-1m
    trigger: true
  - task: annoy
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: Echo
        args: ["Hey! Listen!"]
